export const photo = (n: number) => `/resort/r${n}.webp`;

const lib = (name: string) => `/resort/library/${encodeURIComponent(name)}.jpeg`;

export const PHOTO_LIB = {
  poolFacadeBackdrop: lib("Pool With Hotel Facade Backdrop"),
  exteriorPoolside: lib("Hotel Exterior Architecture Poolside"),
  facadeLitDusk: lib("Hotel Facade Lit Balconies Dusk"),
  facadeLogoNight: lib("Hotel Facade Logo Lit Night"),
  facadePoolNightSign: lib("Hotel Facade Pool Night Sign Lit"),
  facadePoolsideNight: lib("Hotel Facade Poolside Night"),
  lobbyLeather: lib("Lobby Lounge Leather Chairs Light Wall"),
  lobbyStaircasePalms: lib("Lobby Illuminated Staircase Palms"),
  lobbySculpturalChairs: lib("Lobby Lounge Sculptural Chairs Light Disc"),
  lobbyBarDoorway: lib("Lobby Bar View Through Doorway"),
  receptionOnyx: lib("Reception Desk Onyx Marble Symmetric"),
  roomKingCurtain: lib("Guest Room King Bed Curtain"),
  roomBalconyPool: lib("Guest Room Balcony Pool View"),
  roomReadingChair: lib("Guest Room Reading Chair Floor Lamp"),
  roomBalconyResort: lib("Guest Room Balcony Resort View"),
  twinSunburst: lib("Twin Bedroom Sunburst Art"),
  bathroomVanity: lib("Bathroom White Marble Vanity"),
  bathroomShower: lib("Bathroom Marble Shower Rainfall"),
  poolLoungersPalms: lib("Outdoor Pool Loungers Palm Trees"),
  poolLoungersBonsai: lib("Pool Deck Loungers Bonsai Trees"),
  poolDusk: lib("Pool At Dusk Palm Trees"),
  poolRooftop: lib("Pool Rooftop Terrace View"),
  poolSign: lib("Pool With Raha Resort Sign"),
  poolFacadeEvening: lib("Pool With Hotel Facade Evening"),
  poolCabana: lib("Pool View From Cabana"),
  spaIndoor: lib("Indoor Spa Pool Sauna"),
  saunaStones: lib("Sauna Heater Stones"),
  saunaInterior: lib("Wooden Sauna Interior"),
  spaHallway: lib("Spa Hallway Wooden Doors"),
  spaMarbleNiche: lib("Spa Marble Niche Concrete Vanity"),
  diningCoffeeBar: lib("Coffee Bar Marble Counter Seating"),
  diningOpenKitchen: lib("Open Kitchen Marble Counter"),
  diningTerrace: lib("Outdoor Restaurant Terrace Tables"),
  loungeMountainView: lib("Lounge Mountain View Curved Sofa"),
  courtyardFountain: lib("Courtyard Fountain Evening"),
  entranceSignEvening: lib("Raha Resort Entrance Sign Evening"),
  jerichoGoldenHour: lib("Jericho Golden Hour"),
  jerichoMountainsSunset: lib("Jericho Mountains Sunset"),
};

export const PHOTOS = {
  hero: PHOTO_LIB.poolFacadeBackdrop,
  heroAlt: PHOTO_LIB.facadeLitDusk,
  welcome1: PHOTO_LIB.facadeLitDusk,
  welcome2: PHOTO_LIB.roomBalconyPool,
  room1: PHOTO_LIB.roomKingCurtain,
  room2: PHOTO_LIB.roomBalconyPool,
  room3: PHOTO_LIB.roomReadingChair,
  roomExtra: PHOTO_LIB.twinSunburst,
  amenitiesBg: PHOTO_LIB.lobbyStaircasePalms,
  testimonialBg: PHOTO_LIB.poolFacadeEvening,
  ctaBg: PHOTO_LIB.facadePoolNightSign,
  gallery: [
    PHOTO_LIB.facadeLogoNight,
    PHOTO_LIB.lobbySculpturalChairs,
    PHOTO_LIB.poolRooftop,
    PHOTO_LIB.receptionOnyx,
    PHOTO_LIB.courtyardFountain,
    PHOTO_LIB.poolSign,
    PHOTO_LIB.bathroomVanity,
    PHOTO_LIB.entranceSignEvening,
  ],
  pool: [
    PHOTO_LIB.poolLoungersPalms,
    PHOTO_LIB.poolLoungersBonsai,
    PHOTO_LIB.poolDusk,
    PHOTO_LIB.poolCabana,
  ],
  spa: [
    PHOTO_LIB.spaIndoor,
    PHOTO_LIB.saunaInterior,
    PHOTO_LIB.saunaStones,
    PHOTO_LIB.spaHallway,
    PHOTO_LIB.spaMarbleNiche,
  ],
  dining: [
    PHOTO_LIB.diningCoffeeBar,
    PHOTO_LIB.diningOpenKitchen,
    PHOTO_LIB.diningTerrace,
  ],
  gym: [photo(29), photo(30), photo(31)],
  events: [PHOTO_LIB.lobbyBarDoorway, PHOTO_LIB.facadePoolsideNight],
  tours: [photo(34), photo(35), photo(36)],
};

export const ALL_PHOTOS = [
  ...Object.values(PHOTO_LIB),
  ...Array.from({ length: 36 }, (_, i) => photo(i + 1)),
];
